# -*- coding: utf-8 -*-
"""portscanner.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13wuhwRa1DCGZXXH9hF7WCYpmKxOMjvX3
"""

import argparse
import os
import socket
import sys
from datetime import datetime

# argparse adjustments made with AI assistant
# other optimizations adjusted for AI
def parse_arguments():
    parser = argparse.ArgumentParser(
        description="Port scanner for network socket auditing."
    )
    parser.add_argument(
        "-t", "--target",
        help="The target IP address or hostname"
    )
    parser.add_argument(
        "-p", "--ports",
        help="The port range to scan separated by a dash (e.g., 20-80)"
    )
    return parser.parse_args()

# clears screen safely on Windows, Linux, and macOS
os.system('cls' if os.name == 'nt' else 'clear')

# introduction to the tool, "Sandshark"
# labled "Version 1.0.00", to be updated when later features are added
print("Sandshark TCP Port Scanner Version 1.0.0.00")
print("\n---------------------------------------------")
print("\nIf any bugs are identified, please report them on the offical repository on GitHub :)")

args = parse_arguments()

# handle target input
if args.target:
    remoteServer = args.target
else:
    remoteServer = input("Enter a remote host IP to scan: ")

try:
    remoteServerIP = socket.gethostbyname(remoteServer)
except socket.gaierror:
    print("\n[!] Hostname could not be resolved. Terminating scan.")
    sys.exit()

# handle port range input and validation
if args.ports:
    port_range_str = args.ports
else:
    port_range_str = input("Please enter port range for scan (example, 20-80): ")

try:
    # split the string by the dash and convert to integers
    start_port, end_port = map(int, port_range_str.split("-"))

    # validate logic
    if start_port < 1 or end_port > 65535 or start_port > end_port:
        raise ValueError
except ValueError:
    print("\n[!] Invalid port range. Please use format 'start-end' between 1-65535 (example: 21-443).")
    sys.exit()

# show scanning data output
print("_" * 60)
print(f"Please wait, scanning remote host: {remoteServerIP}")
print(f"Scanning ports: {start_port} through {end_port}")
print(f"Time started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
print("_" * 60)

# execution time
t1 = datetime.now()

try:
    # dynamically use the validated start and end ports
    for port in range(start_port, end_port + 1):
        try:
            sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            sock.settimeout(0.5)

            result = sock.connect_ex((remoteServerIP, port))
            if result == 0:
                print(f"Port {port}: Open")

            sock.close()

        except (socket.timeout, socket.error):
            sock.close()
            continue

except KeyboardInterrupt:
    print("\n[!] Scan interrupted (Ctrl+C).")
    sys.exit()

# total execution duration
t2 = datetime.now()
total_time = t2 - t1

print("_" * 60)
print(f"Scanning completed in: {total_time}")
print("_" * 60)